### ISSUE TITLE
How to use Arkitekt STandalone in a Class?

### ISSUE THREAD

**Issue by beniroquai** [openUC2/imswitch-arkitekt-next#1]
@jhnnsrs When using Arkitet-next inside a python class I get the following error. This is the place where I have implemented the ImSwitch plugin. Probably a completely stupid idea. It's not a QT app!

```py 
ERROR:imswitch:[main] Could not find type hint for self in generate_n_string. Please provide a type hint (or default) for this argument.
2024-11-01 23:05:19 ERROR [main] Traceback (most recent call last):
  File "/Users/bene/Dropbox/Dokumente/Promotion/PROJECTS/MicronController/ImSwitch/imswitch/imcontrol/controller/ImConMainController.py", line 58, in __init__
    (getattr(controllers, f'{widgetKey}Controller')
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'imswitch.imcontrol.controller.controllers' has no attribute 'imswitch_arkitekt_nextController'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bene/Dropbox/Dokumente/Promotion/PROJECTS/MicronController/ImSwitch/imswitch/__main__.py", line 146, in main
    view, controller = modulePkg.getMainViewAndController(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/Dropbox/Dokumente/Promotion/PROJECTS/MicronController/ImSwitch/imswitch/imcontrol/__init__.py", line 89, in getMainViewAndController
    raise e
  File "/Users/bene/Dropbox/Dokumente/Promotion/PROJECTS/MicronController/ImSwitch/imswitch/imcontrol/__init__.py", line 84, in getMainViewAndController
    controller = ImConMainController(options, setupInfo, view, moduleCommChannel)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/Dropbox/Dokumente/Promotion/PROJECTS/MicronController/ImSwitch/imswitch/imcontrol/controller/ImConMainController.py", line 67, in __init__
    packageController = entry_point.load()
                        ^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/imswitch311/lib/python3.11/site-packages/pkg_resources/__init__.py", line 2781, in load
    return self.resolve()
           ^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/imswitch311/lib/python3.11/site-packages/pkg_resources/__init__.py", line 2787, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/Downloads/imswitch-arkitekt-next/src/imswitch_arkitekt_next/__init__.py", line 3, in <module>
    from .imswitch_arkitekt_next_controller import *
  File "/Users/bene/Downloads/imswitch-arkitekt-next/src/imswitch_arkitekt_next/imswitch_arkitekt_next_controller.py", line 14, in <module>
    class imswitch_arkitekt_next_controller(ImConWidgetController):
  File "/Users/bene/Downloads/imswitch-arkitekt-next/src/imswitch_arkitekt_next/imswitch_arkitekt_next_controller.py", line 25, in imswitch_arkitekt_next_controller
    @register
     ^^^^^^^^
  File "/Users/bene/mambaforge/envs/imswitch311/lib/python3.11/site-packages/rekuest_next/register.py", line 225, in register
    definition, actor_builder = register_func(
                                ^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/imswitch311/lib/python3.11/site-packages/rekuest_next/register.py", line 96, in register_func
    definition, actor_builder = actifier(
                                ^^^^^^^^^
  File "/Users/bene/mambaforge/envs/imswitch311/lib/python3.11/site-packages/rekuest_next/actors/actify.py", line 89, in reactify
    definition = prepare_definition(
                 ^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/imswitch311/lib/python3.11/site-packages/rekuest_next/definition/define.py", line 834, in prepare_definition
    raise DefinitionError(
rekuest_next.definition.errors.DefinitionError: Could not find type hint for self in generate_n_string. Please provide a type hint (or default) for this argument.

ERROR:imswitch:[main] Traceback (most recent call last):
  File "/Users/bene/Dropbox/Dokumente/Promotion/PROJECTS/MicronController/ImSwitch/imswitch/imcontrol/controller/ImConMainController.py", line 58, in __init__
    (getattr(controllers, f'{widgetKey}Controller')
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'imswitch.imcontrol.controller.controllers' has no attribute 'imswitch_arkitekt_nextController'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bene/Dropbox/Dokumente/Promotion/PROJECTS/MicronController/ImSwitch/imswitch/__main__.py", line 146, in main
    view, controller = modulePkg.getMainViewAndController(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/Dropbox/Dokumente/Promotion/PROJECTS/MicronController/ImSwitch/imswitch/imcontrol/__init__.py", line 89, in getMainViewAndController
    raise e
  File "/Users/bene/Dropbox/Dokumente/Promotion/PROJECTS/MicronController/ImSwitch/imswitch/imcontrol/__init__.py", line 84, in getMainViewAndController
    controller = ImConMainController(options, setupInfo, view, moduleCommChannel)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/Dropbox/Dokumente/Promotion/PROJECTS/MicronController/ImSwitch/imswitch/imcontrol/controller/ImConMainController.py", line 67, in __init__
    packageController = entry_point.load()
                        ^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/imswitch311/lib/python3.11/site-packages/pkg_resources/__init__.py", line 2781, in load
    return self.resolve()
           ^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/imswitch311/lib/python3.11/site-packages/pkg_resources/__init__.py", line 2787, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/Downloads/imswitch-arkitekt-next/src/imswitch_arkitekt_next/__init__.py", line 3, in <module>
    from .imswitch_arkitekt_next_controller import *
  File "/Users/bene/Downloads/imswitch-arkitekt-next/src/imswitch_arkitekt_next/imswitch_arkitekt_next_controller.py", line 14, in <module>
    class imswitch_arkitekt_next_controller(ImConWidgetController):
  File "/Users/bene/Downloads/imswitch-arkitekt-next/src/imswitch_arkitekt_next/imswitch_arkitekt_next_controller.py", line 25, in imswitch_arkitekt_next_controller
    @register
     ^^^^^^^^
  File "/Users/bene/mambaforge/envs/imswitch311/lib/python3.11/site-packages/rekuest_next/register.py", line 225, in register
    definition, actor_builder = register_func(
                                ^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/imswitch311/lib/python3.11/site-packages/rekuest_next/register.py", line 96, in register_func
    definition, actor_builder = actifier(
                                ^^^^^^^^^
  File "/Users/bene/mambaforge/envs/imswitch311/lib/python3.11/site-packages/rekuest_next/actors/actify.py", line 89, in reactify
    definition = prepare_definition(
                 ^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/imswitch311/lib/python3.11/site-packages/rekuest_next/definition/define.py", line 834, in prepare_definition
    raise DefinitionError(
rekuest_next.definition.errors.DefinitionError: Could not find type hint for self in generate_n_string. Please provide a type hint (or default) for this argument.

2024-11-01 23:05:19 INFO [main] init done
INFO:imswitch:[main] init done
```

**Comment by jhnnsrs** [comment]
Not a completely stupid idea. Pretty reasonable actually :D however a few things to consider:

A) When you are registering a function all parameters need to be resolvable on invocation (from arkitekt) and that includes self: if you use the global register function it expects all parameter to be passed on invocation and checks if it is registerable as a structure in arkitekt (like Image, or basic types like int and float). As you want self  to be bound to the instance you need to register the ''instance bound" function directly with the app. 

I.e 

On init 
`
def __init__(self):
       self.app = easy(...)
       self.app.register(self.generate_n_strings)

def generate_n_strings(self, n:int)
       ....
` 

Like that self is already bound and will correctly resolve.

B) the way you are currently running the app (via app.run()) will completely block the main thread. While I am happy to lead you to a 'runAsTask' implementaion with a task handle be aware that you should handle a shutdown of the application or a uninstallation of the plugin more gracefully by canceling the task (and the associated thread).

That's a larger problem with the 'noqt' implementation in general and will also apply to the fastapi server, as you now have 'loose threads' that are now longer managed by a governing event loop (qt's).

So my question: what's your plan there? ;)

Hope that helps

**Comment by beniroquai** [comment]
Thanks for clarification. That makes a lot of sense ;-) 
I have wrapped it into this syntax and start the "app" in a thread. I'll deal with proper killing later. However, when I work like that arkitekt is complaining with the following error message: 

```py
2024-11-02 12:34:36 DEBUG [imswitch_arkitekt_next_controller] Start Arkitekt Runtime
DEBUG:imswitch:[imswitch_arkitekt_next_controller] Start Arkitekt Runtime
58.74s - thread._ident is None in _get_related_thread!
Exception in thread Thread-9 (run):
Traceback (most recent call last):
  File "/Users/bene/mambaforge/envs/imswitch311/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/bene/mambaforge/envs/imswitch311/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/bene/mambaforge/envs/imswitch311/lib/python3.11/site-packages/arkitekt_next/apps/types.py", line 33, in run
    self.services["rekuest"].run()
  File "/Users/bene/mambaforge/envs/imswitch311/lib/python3.11/site-packages/rekuest_next/rekuest.py", line 49, in run
    return unkoil(self.arun, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bene/mambaforge/envs/imswitch311/lib/python3.11/site-packages/koil/helpers.py", line 154, in unkoil
    raise NotImplementedError(
NotImplementedError: You need to be in a Koil() context to use sync() <bound method RekuestNext.arun of ArkitektNextRekuestNext(koil=PedanticKoil(creating_instance=None, running=False, name='KoilLoop', uvify=True, grace_period=None, grant_sync=True, sync_in_async=False), rath=RekuestNextRath(koil=PedanticKoil(creating_instance=None, running=False, name='KoilLoop', uvify=True, grace_period=None, grant_sync=True, sync_in_async=False), link=RekuestNextLinkComposition(koil=PedanticKoil(creating_instance=None, running=False, name='KoilLoop', uvify=True, grace_period=None, grant_sync=True, sync_in_async=False), shrink=ShrinkingLink(koil=PedanticKoil(creating_instance=None, running=False, name='KoilLoop', uvify=True, grace_period=None, grant_sync=True, sync_in_async=False), next=None), dicting=DictingLink(koil=PedanticKoil(creating_instance=None, running=False, name='KoilLoop', uvify=True, grace_period=None, grant_sync=True, sync_in_async=False), next=None, by_alias=True), auth=HerreA```

Any clue what this means?

**Comment by beniroquai** [comment]
Once this works in principle, the next step would be to add functions for move, get image, get 2d scan, etc. 

https://github.com/openUC2/imswitch-arkitekt-next/blob/master/src/imswitch_arkitekt_next/imswitch_arkitekt_next_controller.py#L33

**Comment by jhnnsrs** [comment]
Yes that's expected behaviour, as just handling errors and threads later is not the best strategy :P however papa gets what he wants 

`self.app.enter()` will start koil (the async sync compatibility layer) in another thread and then you can start the run call in yet another thread. Not sure how you would like to stop it then later but I guess arkitekt will be always running? :P otherwise I can add in an runDetached() function that returns a handle to the running app and allows for cancelation?
